### ISSUE TITLE
Exception during package creation with unmet autodep

### ISSUE THREAD

**Issue by Staudey** [getsolus/ypkg#77]
While I was testing the current `fakeroot` symlink issue, I ran into an exception building a test package that was slightly unexpected. When building [this package.yml](https://raw.githubusercontent.com/Staudey/packages/30bc1a3c4a0c340a755758f34fcbc9bcfc66b4e6/packages/f/fakeroot-test/package.yml) without listing `libglvnd` as a builddep, the following exception occurs:

```
[...]
[Dependency] /usr/lib64/lib1.so adds dependency on libXrender.so.1 from libxrender
[Package] Creating /home/build/work/fakeroot-test-devel-1-1-1-x86_64.eopkg ...
Traceback (most recent call last):
  File "/tmp/onefile_14086_1716925137_855457/ypkg", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/tmp/onefile_14086_1716925137_855457/ypkg-build", line 19, in <module multidist-2-ypkg-build>
  File "/tmp/onefile_14086_1716925137_855457/ypkg2/main.py", line 105, in main
  File "/tmp/onefile_14086_1716925137_855457/ypkg2/main.py", line 503, in build_package
  File "/tmp/onefile_14086_1716925137_855457/ypkg2/metadata.py", line 417, in create_eopkg
  File "/tmp/onefile_14086_1716925137_855457/ypkg2/metadata.py", line 388, in create_meta_xml
  File "/tmp/onefile_14086_1716925137_855457/ypkg2/metadata.py", line 344, in handle_dependencies
  File "/tmp/onefile_14086_1716925137_855457/pisi/db/installdb.py", line 272, in get_package
  File "/tmp/onefile_14086_1716925137_855457/pisi/db/installdb.py", line 377, in package_path
Exception: Package libglvnd is not installed
 ✗  Failed to build packages err="Failed to start build of package, reason: exit status 1\n"
task: Failed to run task "build": exit status 1
```

I don't think this is the intended behaviour. At least I don't remember this happening before.

**Comment by davidjharder** [comment]
Ran into this with rawstudio prior to adding `libgtk-2-devel` https://github.com/getsolus/packages/pull/4284
